import { readFile, access } from "node:fs/promises";
import { execFileSync } from "node:child_process";

const manifest = JSON.parse(await readFile("manifest.json", "utf8"));
if (manifest.manifest_version !== 3) throw new Error("必须使用 Manifest V3");
if (!manifest.chrome_url_overrides?.newtab) throw new Error("缺少新标签页入口");

const required = [manifest.chrome_url_overrides.newtab, ...Object.values(manifest.icons), "tools.html", "src/app.js", "src/data.js", "src/storage.js", "src/weather.js", "src/wallpapers.js", "src/market.js", "src/bookmarks.js", "src/commands.js", "src/tools.js", "src/styles.css", "src/styles-extra.css", "src/tools.css", "src/tools-extra.css", "src/tools-v22.css"];
await Promise.all(required.map((path) => access(path)));
for (const file of required.filter((path) => path.endsWith(".js"))) execFileSync(process.execPath, ["--check", file], { stdio: "inherit" });

const html = await readFile(manifest.chrome_url_overrides.newtab, "utf8");
if (!html.includes('src/app.js')) throw new Error("页面未引用应用入口");
const toolsHtml = await readFile("tools.html", "utf8");
if (!toolsHtml.includes('src/tools.js')) throw new Error("工具页未引用应用入口");
const navTools = [...toolsHtml.matchAll(/data-tool="([^"]+)"/g)].map(match => match[1]);
const panels = new Set([...toolsHtml.matchAll(/data-panel="([^"]+)"/g)].map(match => match[1]));
for (const tool of navTools) if (!panels.has(tool)) throw new Error(`工具 ${tool} 缺少对应面板`);
const { WALLPAPERS, DEFAULT_LINKS, DEFAULT_SETTINGS } = await import("../src/data.js");
if (WALLPAPERS.length < 24 || new Set(WALLPAPERS.map(item => item.category)).size < 6) throw new Error("壁纸数量或分类不足");
const { WALLPAPER_SOURCES, getBirdCategories, getHaoDisplayUrl, loadBirdWallpapers, searchWallpapers } = await import("../src/wallpapers.js");
if (![getBirdCategories, loadBirdWallpapers, searchWallpapers].every(item => typeof item === "function")) throw new Error("小鸟壁纸分类、分页或关键词搜索未正确配置");
if (!WALLPAPER_SOURCES.some(source => source.id === "bird" && source.bird) || WALLPAPER_SOURCES.some(source => /360|wallhaven|picsum/i.test(source.id))) throw new Error("小鸟壁纸源替换不完整");
if (!WALLPAPER_SOURCES.some(item => item.id === "hao-wallpaper" && typeof item.load === "function") || WALLPAPER_SOURCES.some(item => item.id === "timeline")) throw new Error("哲风壁纸或拾光移除状态不正确");
if (!getHaoDisplayUrl("/link/common/file/getCroppingImg/123").includes("/previewFileImg/123")) throw new Error("哲风壁纸背景仍在使用列表缩略图");
for (const host of ["http://wp.birdpaper.com.cn/*", "https://haowallpaper.com/*"]) if (!manifest.host_permissions.includes(host)) throw new Error(`${host} 权限缺失`);
if (!manifest.host_permissions.includes("https://qt.gtimg.cn/*")) throw new Error("腾讯行情接口权限缺失");
if (manifest.host_permissions.some(host => /timeline|nguaduot/i.test(host))) throw new Error("仍包含拾光壁纸接口权限");
const appSource = await readFile("src/app.js", "utf8");
const stylesSource = await readFile("src/styles.css", "utf8");
if (!Number.isFinite(DEFAULT_SETTINGS.shortcutBlur) || !appSource.includes("shortcutBlurRange") || !stylesSource.includes("--shortcut-blur")) throw new Error("快捷方式背景模糊度设置未完整接入");
if (!stylesSource.includes("background-size:cover") || !stylesSource.includes("transform:none")) throw new Error("壁纸未按无额外缩放的全屏模式显示");
const { DEFAULT_WATCHLIST } = await import("../src/market.js");
if (DEFAULT_WATCHLIST.length !== 8 || !appSource.includes("bookmarkPicker") || !appSource.includes("importBookmarksSettings") || !appSource.includes("data-edit") || !html.includes("marketList")) throw new Error("盯盘或快捷方式编辑、设置页收藏夹导入功能未完整接入");
for (const category of ["shopping", "blog", "dev", "ai"]) if (DEFAULT_LINKS.filter(link => link.category === category).length < 10) throw new Error(`${category} 默认网站不足`);
const { COMMAND_CATALOG } = await import("../src/commands.js");
for (const shell of ["linux", "powershell", "cmd"]) if (COMMAND_CATALOG.filter(item => item[0] === shell).length < 25) throw new Error(`${shell} 命令数量不足`);
if (/https?:\/\/[^"']+\.js/.test(html)) throw new Error("扩展不能引用远程脚本");
console.log(`✓ Manifest V${manifest.manifest_version} 有效`);
console.log(`✓ ${required.length} 个必要文件存在`);
console.log("✓ JavaScript 语法与扩展 CSP 基础检查通过");
console.log(`✓ ${navTools.length} 个工具面板、${WALLPAPERS.length} 张分类壁纸检查通过`);
console.log(`✓ ${WALLPAPER_SOURCES.length} 个壁纸入口及小鸟分类、分页、tag 搜索检查通过`);
console.log(`✓ ${COMMAND_CATALOG.length} 条跨平台命令及博客分类检查通过`);
